version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "db_auth"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root12345"
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    